# Generated by Django 3.2.8 on 2022-12-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_subscribing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribing',
        ),
    ]
